// @generated by scripts/gen_example_tests.sh — DO NOT EDIT MANUALLY.
// Run `bash scripts/gen_example_tests.sh` to regenerate this file.
//
// Integration tests that run each example file through the loft binary.
//
// FFI examples are skipped because they require native shared libraries
// (e.g. libm.so.6) that are not guaranteed to be present in all environments.
// Network / external-package examples are included but marked #[ignore].
use std::path::Path;
use std::process::Command;

const LOFT: &str = env!("CARGO_BIN_EXE_loft");

/// Run a `.lf` file through the loft binary and assert it exits successfully.
///
/// `cwd` is the working directory passed to the process; use `Some(dir)` for
/// examples that `learn` relative paths (modules), otherwise pass `None`.
fn run_example(file: impl AsRef<Path>, cwd: Option<&Path>) {
    let file = file.as_ref();
    let mut cmd = Command::new(LOFT);
    cmd.arg("--allow-all")
        .arg(file.to_str().expect("non-UTF-8 path"));

    if let Some(dir) = cwd {
        cmd.current_dir(dir);
    }

    let output = cmd
        .output()
        .unwrap_or_else(|e| panic!("failed to spawn loft for {:?}: {}", file, e));

    if !output.status.success() {
        panic!(
            "example {:?} failed with status {}\n--- stdout ---\n{}\n--- stderr ---\n{}",
            file,
            output.status,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );
    }
}
// ---------------------------------------------------------------------------
// Individual example tests
// ---------------------------------------------------------------------------

#[test]
fn example_enum_patterns() {
    run_example("examples/enum_patterns.lf", None);
}

#[test]
fn example_error_handling() {
    run_example("examples/error_handling.lf", None);
}

#[test]
fn example_factorial() {
    run_example("examples/factorial.lf", None);
}

#[test]
fn example_mutable_capture() {
    run_example("examples/mutable_capture.lf", None);
}

#[test]
fn example_optional_return() {
    run_example("examples/optional_return.lf", None);
}

#[test]
fn example_option_result() {
    run_example("examples/option_result.lf", None);
}

#[test]
fn example_showcase() {
    run_example("examples/showcase.lf", None);
}

#[test]
fn example_test_error_prop() {
    run_example("examples/test_error_prop.lf", None);
}

#[test]
fn example_trait_example() {
    run_example("examples/trait_example.lf", None);
}

// ---------------------------------------------------------------------------
// Examples that require external resources (run with --ignored)
// ---------------------------------------------------------------------------

/// Requires external resources; run manually with
/// `cargo test -- --ignored` once they are available.
#[test]
#[ignore = "requires network access or the 'std' package to be installed"]
fn example_web_api_demo() {
    run_example("examples/web_api_demo.lf", None);
}

// ---------------------------------------------------------------------------
// Module examples
// ---------------------------------------------------------------------------

/// Module examples use `learn` with relative paths, so the process must run
/// from the directory that contains the module files.
#[test]
fn example_modules_main() {
    let cwd = Path::new("examples/modules");
    run_example(
        Path::new("examples/modules/main.lf")
            .canonicalize()
            .unwrap_or_else(|_| Path::new("examples/modules/main.lf").to_path_buf()),
        Some(cwd),
    );
}
// ---------------------------------------------------------------------------
// FFI examples are skipped – they require native shared libraries at runtime.
//
// #[test]
// fn example_ffi_example() { run_example("examples/ffi_example.lf", None); }
// #[test]
// fn example_ffi_simple() { run_example("examples/ffi_simple.lf", None); }
// #[test]
// fn example_ffi_wrapper() { run_example("examples/ffi_wrapper.lf", None); }
// ---------------------------------------------------------------------------
